### ISSUE TITLE
How to change the icon color of toolbar ?

### ISSUE THREAD

**Issue by KAGEYAM4** [StickySli/qttabbar-dark-mode-skin#2]
![image](https://user-images.githubusercontent.com/75798544/179368772-efae2d9f-3ba2-4556-a572-a97fe5a73160.png)

**Comment by KAGEYAM4** [comment]
also i cannot find this option you mentioned , the image to be exact 

"
For the toolbar background, choose the provided image, otherwise, use the solid color RGB(25,25,25) which has the closest color aproximation to Windows's dark mode.
"

**Comment by StickySli** [comment]
As far as I am aware, the QTTabBar Standard Buttons do not have a way to modify the text color aside from the icons. IMHO, the QTTabBar Standard Buttons are not useful and just add clutter to the windows file explorer. To disable the QTTabBar Standard Buttons, right click on the toolbar, unlock the toolbar, right click on the dots that appeared on the left, and disable the QTTabBar Standard Buttons, then lock the toolbar again.
![image](https://user-images.githubusercontent.com/77287361/179369112-a57b935b-3533-4c95-aa44-1922dd19de77.png)

**Comment by KAGEYAM4** [comment]
ok , but i use groups and recently closed buttons, is there a way to get use of those feature while having buttons disables ?

**Comment by KAGEYAM4** [comment]
ok , checked it, if i right click on empty space i can access the groups and recently closed. thanks
